 1. What is a Python library? Why do we use Python libraries?

Python libraries are collections of pre-written code and functions that extend the capabilities of the Python programming language. They provide a wide range of tools and modules for various tasks, making it easier for developers to work on specific tasks without reinventing the wheel.

We use Python Libraries because it makes Python programming easier and simpler. Since then, we will not need to compose the same code for various projects.

2. What is the difference between Numpy array and List?

Numpy arrays is a typed array, the array in memory stores a homogenous, densely packed numbers.

Python list is a heterogeneous list, the list in memory stores references to objects rather than the number themselves. 

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [8]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr.shape) 
print(arr.size)
print(arr.ndim)

(3, 4)
12
2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [12]:
import numpy as np
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr1[0])

[1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [38]:
import numpy as np
arra_data = np.arange(0, 16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Third and fourth elements of the first and second rows")
print(arra_data[0:2, 2:4])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows
[[2 3]
 [6 7]]


6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [40]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[a % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [41]:
import numpy as np
x = np.random.random((3, 3, 3))
print(x) 

[[[0.02033791 0.04057922 0.09598629]
  [0.93665885 0.55873521 0.15116268]
  [0.8332048  0.4224863  0.83351567]]

 [[0.15341395 0.13600708 0.51729445]
  [0.12124431 0.17768071 0.68354699]
  [0.83385399 0.14921844 0.78115532]]

 [[0.00928951 0.0149978  0.51313871]
  [0.55394533 0.95058361 0.53957088]
  [0.15535252 0.31751784 0.52757301]]]


8. Describe the difference between np.random.r and and np.random.randn?

random. rand() produces random numbers from a uniform distribution over the interval [0, 1), while np. random. randn() generates random numbers from a standard normal distribution.

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [43]:
import numpy
numLabels = 10
X = numpy.random.rand(20,)
offset = numpy.full((20,),0.07) 
Y = numpy.zeros((20,numLabels))

for l in range(numLabels):
    Y[:,l] = X + (l-4.5)*offset

10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [45]:
import numpy as np
 
# making a 3x3 array
gfg = np.array([[1, 2, 3, 4] , [5, 6, 7, 8], [9, 10, 11, 12]])
 
# before transpose
print(gfg, end ='\n\n')
 
# after transpose
print(gfg.transpose())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python:
1. Index wise multiplication
2. Matix multiplication
3. Add both the matics
4. Subtract matrix from B to A
5. Dive matrix B by A

12. Which function in Numpy can be used to swap the byte order of an array?

byteswap() method swaps the bytes of the array elements. It toggles between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place.

13. What is the significance of the np.linalg.inv function?

We use numpy. linalg. inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.

14. What does the np.reshape function do, and how is it used?


Change an Array's Shape Using NumPy reshape() NumPy's reshape() enables you to change the shape of an array into another compatible shape. Not all shapes are compatible since all the elements from the original array needs to fit into the new array. You can use reshape() as either a function or a method.

15. What is broadcasting in Numpy?

numpy.broadcast. The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.